#ifdef IA8_30FPS_COINS
// 0x1600013C
const GeoLayout yellow_coin_geo[] = {
   GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 0xB4, 50),
   GEO_OPEN_NODE(),
      GEO_SWITCH_CASE(8, geo_switch_anim_state),
      GEO_OPEN_NODE(),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 0, coin_seg3_dl_yellow_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 1, coin_seg3_dl_yellow_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 2, coin_seg3_dl_yellow_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 3, coin_seg3_dl_yellow_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 4, coin_seg3_dl_yellow_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 3, coin_seg3_dl_yellow_draw_r),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 2, coin_seg3_dl_yellow_draw_r),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 1, coin_seg3_dl_yellow_draw_r),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x160001A0
const GeoLayout yellow_coin_no_shadow_geo[] = {
   GEO_NODE_START(),
   GEO_OPEN_NODE(),
      GEO_SWITCH_CASE(8, geo_switch_anim_state),
      GEO_OPEN_NODE(),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 0, coin_seg3_dl_yellow_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 1, coin_seg3_dl_yellow_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 2, coin_seg3_dl_yellow_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 3, coin_seg3_dl_yellow_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 4, coin_seg3_dl_yellow_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 3, coin_seg3_dl_yellow_draw_r),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 2, coin_seg3_dl_yellow_draw_r),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 1, coin_seg3_dl_yellow_draw_r),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x16000200
const GeoLayout blue_coin_geo[] = {
   GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 0xB4, 80),
   GEO_OPEN_NODE(),
      GEO_SWITCH_CASE(8, geo_switch_anim_state),
      GEO_OPEN_NODE(),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 0, coin_seg3_dl_blue_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 1, coin_seg3_dl_blue_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 2, coin_seg3_dl_blue_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 3, coin_seg3_dl_blue_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 4, coin_seg3_dl_blue_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 3, coin_seg3_dl_blue_draw_r),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 2, coin_seg3_dl_blue_draw_r),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 1, coin_seg3_dl_blue_draw_r),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x16000264
const GeoLayout blue_coin_no_shadow_geo[] = {
   GEO_NODE_START(),
   GEO_OPEN_NODE(),
      GEO_SWITCH_CASE(8, geo_switch_anim_state),
      GEO_OPEN_NODE(),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 0, coin_seg3_dl_blue_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 1, coin_seg3_dl_blue_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 2, coin_seg3_dl_blue_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 3, coin_seg3_dl_blue_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 4, coin_seg3_dl_blue_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 3, coin_seg3_dl_blue_draw_r),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 2, coin_seg3_dl_blue_draw_r),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 1, coin_seg3_dl_blue_draw_r),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x160002C4
const GeoLayout red_coin_geo[] = {
   GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 0xB4, 80),
   GEO_OPEN_NODE(),
      GEO_SWITCH_CASE(8, geo_switch_anim_state),
      GEO_OPEN_NODE(),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 0, coin_seg3_dl_red_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 1, coin_seg3_dl_red_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 2, coin_seg3_dl_red_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 3, coin_seg3_dl_red_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 4, coin_seg3_dl_red_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 3, coin_seg3_dl_red_draw_r),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 2, coin_seg3_dl_red_draw_r),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 1, coin_seg3_dl_red_draw_r),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x16000328
const GeoLayout red_coin_no_shadow_geo[] = {
   GEO_NODE_START(),
   GEO_OPEN_NODE(),
      GEO_SWITCH_CASE(8, geo_switch_anim_state),
      GEO_OPEN_NODE(),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 0, coin_seg3_dl_red_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 1, coin_seg3_dl_red_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 2, coin_seg3_dl_red_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 3, coin_seg3_dl_red_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 4, coin_seg3_dl_red_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 3, coin_seg3_dl_red_draw_r),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 2, coin_seg3_dl_red_draw_r),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 1, coin_seg3_dl_red_draw_r),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x160002C4
const GeoLayout silver_coin_geo[] = {
   GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 0xB4, 80),
   GEO_OPEN_NODE(),
      GEO_SWITCH_CASE(8, geo_switch_anim_state),
      GEO_OPEN_NODE(),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 0, coin_seg3_dl_secret_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 1, coin_seg3_dl_secret_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 2, coin_seg3_dl_secret_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 3, coin_seg3_dl_secret_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 4, coin_seg3_dl_secret_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 3, coin_seg3_dl_secret_draw_r),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 2, coin_seg3_dl_secret_draw_r),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 1, coin_seg3_dl_secret_draw_r),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x16000328
const GeoLayout silver_coin_no_shadow_geo[] = {
   GEO_NODE_START(),
   GEO_OPEN_NODE(),
      GEO_SWITCH_CASE(8, geo_switch_anim_state),
      GEO_OPEN_NODE(),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 0, coin_seg3_dl_secret_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 1, coin_seg3_dl_secret_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 2, coin_seg3_dl_secret_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 3, coin_seg3_dl_secret_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 4, coin_seg3_dl_secret_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 3, coin_seg3_dl_secret_draw_r),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 2, coin_seg3_dl_secret_draw_r),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 1, coin_seg3_dl_secret_draw_r),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

#else
// 0x1600013C
const GeoLayout yellow_coin_geo[] = {
   GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 0xB4, 50),
   GEO_OPEN_NODE(),
      GEO_SWITCH_CASE(8, geo_switch_anim_state),
      GEO_OPEN_NODE(),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 0, coin_seg3_dl_yellow_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 0, coin_seg3_dl_yellow_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 1, coin_seg3_dl_yellow_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 1, coin_seg3_dl_yellow_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 2, coin_seg3_dl_yellow_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 2, coin_seg3_dl_yellow_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 3, coin_seg3_dl_yellow_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 3, coin_seg3_dl_yellow_draw),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x160001A0
const GeoLayout yellow_coin_no_shadow_geo[] = {
   GEO_NODE_START(),
   GEO_OPEN_NODE(),
      GEO_SWITCH_CASE(8, geo_switch_anim_state),
      GEO_OPEN_NODE(),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 0, coin_seg3_dl_yellow_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 0, coin_seg3_dl_yellow_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 1, coin_seg3_dl_yellow_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 1, coin_seg3_dl_yellow_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 2, coin_seg3_dl_yellow_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 2, coin_seg3_dl_yellow_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 3, coin_seg3_dl_yellow_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 3, coin_seg3_dl_yellow_draw),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x16000200
const GeoLayout blue_coin_geo[] = {
   GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 0xB4, 80),
   GEO_OPEN_NODE(),
      GEO_SWITCH_CASE(8, geo_switch_anim_state),
      GEO_OPEN_NODE(),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 0, coin_seg3_dl_blue_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 0, coin_seg3_dl_blue_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 1, coin_seg3_dl_blue_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 1, coin_seg3_dl_blue_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 2, coin_seg3_dl_blue_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 2, coin_seg3_dl_blue_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 3, coin_seg3_dl_blue_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 3, coin_seg3_dl_blue_draw),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x16000264
const GeoLayout blue_coin_no_shadow_geo[] = {
   GEO_NODE_START(),
   GEO_OPEN_NODE(),
      GEO_SWITCH_CASE(8, geo_switch_anim_state),
      GEO_OPEN_NODE(),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 0, coin_seg3_dl_blue_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 0, coin_seg3_dl_blue_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 1, coin_seg3_dl_blue_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 1, coin_seg3_dl_blue_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 2, coin_seg3_dl_blue_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 2, coin_seg3_dl_blue_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 3, coin_seg3_dl_blue_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 3, coin_seg3_dl_blue_draw),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x160002C4
const GeoLayout red_coin_geo[] = {
   GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 0xB4, 80),
   GEO_OPEN_NODE(),
      GEO_SWITCH_CASE(8, geo_switch_anim_state),
      GEO_OPEN_NODE(),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 0, coin_seg3_dl_red_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 0, coin_seg3_dl_red_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 1, coin_seg3_dl_red_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 1, coin_seg3_dl_red_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 2, coin_seg3_dl_red_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 2, coin_seg3_dl_red_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 3, coin_seg3_dl_red_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 3, coin_seg3_dl_red_draw),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x16000328
const GeoLayout red_coin_no_shadow_geo[] = {
   GEO_NODE_START(),
   GEO_OPEN_NODE(),
      GEO_SWITCH_CASE(8, geo_switch_anim_state),
      GEO_OPEN_NODE(),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 0, coin_seg3_dl_red_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 0, coin_seg3_dl_red_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 1, coin_seg3_dl_red_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 1, coin_seg3_dl_red_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 2, coin_seg3_dl_red_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 2, coin_seg3_dl_red_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 3, coin_seg3_dl_red_draw),
         GEO_BATCH_DISPLAY_LIST(LAYER_OCCLUDE_SILHOUETTE_ALPHA, BATCH_OCCLUDE_SILHOUETTE_ALPHA_COIN_FIRST + 3, coin_seg3_dl_red_draw),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};
#endif
